[global]
    workgroup = WORKGROUP
    server string = LibraryIT Server
    security = user
    map to guest = bad user
    dns proxy = no

    vfs objects = full_audit
    full_audit:prefix = AUDIT|%u|%S
    full_audit:success = connect pwrite
    full_audit:failure = connect pwrite
    full_audit:facility = local7
    full_audit:priority = notice

[ebooks]
    path = /libraryit/ebooks
    browseable = yes
    guest ok = yes
    read only = no

[papers]
    path = /libraryit/papers
    browseable = yes
    guest ok = yes
    read only = no

[docs]
    path = /libraryit/docs
    browseable = yes
    guest ok = yes
    read only = no
    force user = root

[SourceCode]
    path = /libraryit/sourcecode
    browseable = no
    valid users = @staff
    read only = no